services:
  - type: web
    name: movie-recommend-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0
